-- Leisurely Phase 3 — Initial Supabase schema
-- Run via: supabase db push  OR  paste into the SQL Editor in the Supabase dashboard.

-- ─────────────────────────────────────────────────────────────────────────────
-- PLANS
-- days is stored as JSONB (array of DayPlan objects) so the in-app data model
-- maps 1-to-1 without a separate meal_slots table.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS plans (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  name         TEXT NOT NULL DEFAULT 'My Trip',
  start_date   DATE NOT NULL,
  end_date     DATE NOT NULL,
  is_public    BOOLEAN NOT NULL DEFAULT false,
  days         JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- MEALS
-- Full Meal object stored as JSONB (includes ingredients array).
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS meals (
  id         UUID PRIMARY KEY,
  plan_id    UUID REFERENCES plans ON DELETE CASCADE NOT NULL,
  user_id    UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  data       JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- GROCERY ITEMS
-- Aggregated list stored per-plan. Regenerated by the client.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS grocery_items (
  id         UUID PRIMARY KEY,
  plan_id    UUID REFERENCES plans ON DELETE CASCADE NOT NULL,
  user_id    UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  data       JSONB NOT NULL
);

-- ─────────────────────────────────────────────────────────────────────────────
-- NOTES  (bulletin board — not tied to a specific plan)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS notes (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  text       TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- PACKING ITEMS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS packing_items (
  id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  plan_id    UUID REFERENCES plans ON DELETE CASCADE,
  user_id    UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  text       TEXT NOT NULL,
  category   TEXT NOT NULL DEFAULT 'misc',
  packed     BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- updated_at trigger (applied to plans and meals)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER plans_updated_at  BEFORE UPDATE ON plans  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER meals_updated_at  BEFORE UPDATE ON meals  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ─────────────────────────────────────────────────────────────────────────────
-- ROW-LEVEL SECURITY
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE plans         ENABLE ROW LEVEL SECURITY;
ALTER TABLE meals         ENABLE ROW LEVEL SECURITY;
ALTER TABLE grocery_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE notes         ENABLE ROW LEVEL SECURITY;
ALTER TABLE packing_items ENABLE ROW LEVEL SECURITY;

-- Plans: owner can do everything; authenticated users can read public plans
CREATE POLICY "plans_owner"  ON plans FOR ALL  USING (auth.uid() = user_id);
CREATE POLICY "plans_public" ON plans FOR SELECT USING (is_public = true AND auth.role() = 'authenticated');

-- Meals, grocery_items, packing_items: owner only
CREATE POLICY "meals_owner"   ON meals         FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "grocery_owner" ON grocery_items FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "packing_owner" ON packing_items FOR ALL USING (auth.uid() = user_id);

-- Notes: owner only
CREATE POLICY "notes_owner" ON notes FOR ALL USING (auth.uid() = user_id);

-- ─────────────────────────────────────────────────────────────────────────────
-- REALTIME
-- Enable Realtime publications for collaborative updates.
-- ─────────────────────────────────────────────────────────────────────────────
BEGIN;
  DROP PUBLICATION IF EXISTS supabase_realtime;
  CREATE PUBLICATION supabase_realtime FOR TABLE plans, meals, grocery_items, notes, packing_items;
COMMIT;
